apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep-lab
  template:
    metadata:
      labels:
        app: dep-lab
    spec:
      containers:
      - image: http:2.2
        name: http

