apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
  namespace: orange
spec:
  containers:
  - image: nginx:1.14
    name: nginxpod
    env:
    - name: MYENV
      value: "testvalue"

